# Generated by Django 6.0.2 on 2026-02-10 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_alter_course_description_alter_lesson_description"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True, verbose_name="дата платежа")),
                ("payment_amount", models.IntegerField(verbose_name="сумма платежа")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("Наличные", "Наличные"), ("Перевод", "Перевод")],
                        max_length=20,
                    ),
                ),
                (
                    "session_id_course",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="id сессии"
                    ),
                ),
                (
                    "link_course",
                    models.URLField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="ссылка на оплату",
                    ),
                ),
                (
                    "session_id_lesson",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="id сессии"
                    ),
                ),
                (
                    "link_lesson",
                    models.URLField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="ссылка на оплату",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paid_course",
                        to="lms.course",
                        verbose_name="оплаченный курс",
                    ),
                ),
                (
                    "lessons",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paid_lesson",
                        to="lms.lesson",
                        verbose_name="оплаченный урок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="платежи",
                    ),
                ),
            ],
        ),
    ]
