# Generated by Django 6.0.2 on 2026-02-10 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payments",
            old_name="course",
            new_name="course_paid",
        ),
        migrations.RenameField(
            model_name="payments",
            old_name="lessons",
            new_name="lesson_paid",
        ),
        migrations.RenameField(
            model_name="payments",
            old_name="link_lesson",
            new_name="link_pay",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="user",
        ),
        migrations.AddField(
            model_name="payments",
            name="user_payer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Плательщик",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод")], max_length=20
            ),
        ),
    ]
