# Generated by Django 6.0.2 on 2026-02-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_course_payments_course_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Укажите сумму оплаты",
                max_digits=7,
                verbose_name="Сумма оплаты",
            ),
        ),
    ]
