# Generated by Django 6.0.2 on 2026-02-13 18:12

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payments_payment_method"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.Manager()),
            ],
        ),
    ]
